imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@HBAdminBundle/Resources/config/services.yml" }
    - { resource: "@HBAuthorBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration


framework:
    #esi: ~
    translator: { fallbacks: ['ru'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    serializer: ~
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    ide: 'phpstorm://open?url=file://%%f&line=%%l'

# Twig Configuration
twig:
    globals:
        upload_care_public: '%upload_care_public%'
        upload_care_secret: '%upload_care_secret%'
        #upload_care_sources: 'file camera url facebook gdrive gphotos dropbox instagram evernote flickr skydrive vk'
        upload_care_sources: 'file gdrive gphotos dropbox'
        max_file_size: 1610612736
        intercom_app_id: '%intercom_app_id%'
        segment_key: '%segment_key%'
        intercom_secret: '%intercom_secret%'
        oto_offer_formats_tooltip: 'Форматы .doc, .docx, .pdf'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    spool: { type: memory }

sentry:
    dsn: "%sentry_dsn%"
    options:
        excluded_exceptions:
            - \AMQPQueueException
            - \HB\AdminBundle\Exception\ConsumerErrorException


sensio_framework_extra:
    router:
        annotations: false
    request:
        converters: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template

fos_ck_editor:
    input_sync: true
    configs:
        lessons_config:
            toolbar: "lessons_toolbar"
        organic_config:
            toolbar: "organic_toolbar"
    toolbars:
        configs:
            lessons_toolbar: [ ["Format", "/",
                                "Bold", "Italic", "Underline", "Link", "Blockquote", "/",
                                "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "/",
                                "BulletedList", "NumberedList", "/",
                                "TextColor", "Image"
                               ] ]
            organic_toolbar: [ ["Source", "/",
                                "Bold", "Italic", "Underline", "/",
                                "NumberedList", "BulletedList", "Outdent", "Indent", "Link", "/",
                                "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "/",
                                "TextColor", "BGColor", "Image"
                               ] ]