<?php

declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190921111111 extends AbstractMigration
{
    public function getDescription() : string
    {
        return 'Init migration';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE action_log (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, user_id INT DEFAULT NULL, object VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, object_id INT DEFAULT NULL, changeset LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, time DATETIME NOT NULL, published TINYINT(1) NOT NULL, funnel VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, funnel_id INT DEFAULT NULL, INDEX IDX_B2C5F685591CC992 (course_id), INDEX IDX_B2C5F685A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE additional_block (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_logo (id INT AUTO_INCREMENT NOT NULL, company_logo_file_id INT DEFAULT NULL, INDEX IDX_A7E380FD592C59D2 (company_logo_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, sale_funnel_organic_id INT DEFAULT NULL, sale_funnel_broken_basket_id INT DEFAULT NULL, sale_funnel_post_sale_id INT DEFAULT NULL, sale_funnel_cross_sale_id INT DEFAULT NULL, sale_funnel_hot_leads_id INT DEFAULT NULL, sale_funnel_mini_course_id INT DEFAULT NULL, sale_funnel_walker_start_id INT DEFAULT NULL, sale_funnel_author_club_id INT DEFAULT NULL, sale_funnel_educational_id INT DEFAULT NULL, status VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, info_title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, info_sub_title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, sandbox TINYINT(1) NOT NULL, integr_google_analytics LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_facebook_pixel LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_yandex_metrics LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_vk LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_ok LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_twitter LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_linkedin LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, integr_pinterest LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, stop_lessons_previous_lessons_mark TINYINT(1) NOT NULL, stop_lessons_viewed_videos_mark TINYINT(1) NOT NULL, stop_lessons_test_passed_mark TINYINT(1) NOT NULL, stop_lessons_tests_min_percent_passed DOUBLE PRECISION DEFAULT NULL, stop_lessons_tests_max_attempts INT DEFAULT NULL, had_moderate_request TINYINT(1) NOT NULL, link_online_school VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, link_payment_page VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, teachable_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_169E6FB91EDF53A6 (sale_funnel_organic_id), UNIQUE INDEX UNIQ_169E6FB9A3CF9AB1 (sale_funnel_broken_basket_id), UNIQUE INDEX UNIQ_169E6FB92592F9B4 (sale_funnel_post_sale_id), UNIQUE INDEX UNIQ_169E6FB98B3C19F (sale_funnel_cross_sale_id), UNIQUE INDEX UNIQ_169E6FB987B0DB59 (sale_funnel_hot_leads_id), UNIQUE INDEX UNIQ_169E6FB94E8F5943 (sale_funnel_mini_course_id), UNIQUE INDEX UNIQ_169E6FB91C972077 (sale_funnel_walker_start_id), UNIQUE INDEX UNIQ_169E6FB914A68D63 (sale_funnel_author_club_id), UNIQUE INDEX UNIQ_169E6FB9DB928C1 (sale_funnel_educational_id), INDEX IDX_169E6FB99395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_block (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, block_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, priority INT NOT NULL, UNIQUE INDEX UNIQ_6AB090CA2B36786B (title), UNIQUE INDEX UNIQ_6AB090CA4AB00552 (block_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer (id INT AUTO_INCREMENT NOT NULL, file_id INT DEFAULT NULL, role_id INT DEFAULT NULL, packet_id INT DEFAULT NULL, requested_packet_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, producer_id INT DEFAULT NULL, payment_account_id INT DEFAULT NULL, transferwise_account_id INT DEFAULT NULL, date_created_at DATETIME NOT NULL, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, about_info LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, password VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, firstName VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, surname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, status TINYINT(1) NOT NULL, password_recovery_hash VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, signup_hash VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, confirm_sms_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, zapier_profile_complited_event TINYINT(1) NOT NULL, packet_subscription SMALLINT NOT NULL, last_activity_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_81398E09E7927C74 (email), UNIQUE INDEX UNIQ_81398E09AE9DDE6F (payment_account_id), UNIQUE INDEX UNIQ_81398E09DC4BA2A (transferwise_account_id), INDEX IDX_81398E0993CB796C (file_id), INDEX IDX_81398E09D60322AC (role_id), INDEX IDX_81398E09FE090D6B (packet_id), INDEX IDX_81398E09E77ED66 (requested_packet_id), INDEX IDX_81398E097E3C61F9 (owner_id), INDEX IDX_81398E0989B658FE (producer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_action (id INT AUTO_INCREMENT NOT NULL, id_customer INT DEFAULT NULL, status VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, is_viewed TINYINT(1) NOT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, INDEX IDX_F60950C3D1E2629C (id_customer), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_packet (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_payment (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, amount DOUBLE PRECISION NOT NULL, payment_date DATETIME NOT NULL, created_at DATETIME NOT NULL, creator_id INT DEFAULT NULL, details LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, start_date DATETIME DEFAULT NULL, end_date DATETIME DEFAULT NULL, INDEX IDX_71F520B39395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_payment_account (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, paypal_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, payoneer_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_customer_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_swift_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_account_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, bank_correspondent VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_1F571ED49395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_payment_report (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, report_file_id INT DEFAULT NULL, report_date DATETIME NOT NULL, UNIQUE INDEX customer_report_date_unique (customer_id, report_date), INDEX IDX_787AD8D89395C3F3 (customer_id), INDEX IDX_787AD8D8F352046C (report_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_role (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_3F82E1D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer_transferwise_account (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, account_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, zip VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_first_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_surname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_patronymic VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ua_full_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ua_last_four_digits INT DEFAULT NULL, ua_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_region VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_local_account VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_local_bank_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, ru_card_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_3FA53E409395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE educational_letter (id INT AUTO_INCREMENT NOT NULL, lesson_file_id INT DEFAULT NULL, article_file_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_66DCD9A366B72BCB (lesson_file_id), INDEX IDX_66DCD9A37E193DDB (article_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feedback_video (id INT AUTO_INCREMENT NOT NULL, feedback_video_file_id INT DEFAULT NULL, feed_back_author VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_E866434962BB4E6A (feedback_video_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE funnel_priority (id INT AUTO_INCREMENT NOT NULL, course_id INT NOT NULL, funnel_key VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, priority INT NOT NULL, UNIQUE INDEX course_funnel_priority_unique (course_id, funnel_key), INDEX IDX_AC9A754B591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE knowledge_skills (id INT AUTO_INCREMENT NOT NULL, skill LONGTEXT NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lesson (id INT AUTO_INCREMENT NOT NULL, id_section INT NOT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, isFree TINYINT(1) NOT NULL, priority INT NOT NULL, INDEX IDX_F87474F3F3EED39F (id_section), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lesson_element (id INT AUTO_INCREMENT NOT NULL, id_lesson INT NOT NULL, file_id INT DEFAULT NULL, lesson_element_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, content_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, content_iframe LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, priority INT NOT NULL, consultation_at DATETIME DEFAULT NULL, webinar_at DATETIME DEFAULT NULL, consultation_timezone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, webinar_timezone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_B43C0C9EDE43C11E (id_lesson), INDEX IDX_B43C0C9E93CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lesson_section (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, by_date DATETIME DEFAULT NULL, after_days INT DEFAULT NULL, priority INT NOT NULL, INDEX IDX_D80F284830A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lesson_sections_price_blocks (lesson_section_id INT NOT NULL, price_block_id INT NOT NULL, INDEX IDX_CD7B118AD52AAAAB (lesson_section_id), INDEX IDX_CD7B118A8B5BB91B (price_block_id), PRIMARY KEY(lesson_section_id, price_block_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE managers_authors (manager_id INT NOT NULL, author_id INT NOT NULL, INDEX IDX_6AEBC2FF783E3463 (manager_id), INDEX IDX_6AEBC2FFF675F31B (author_id), PRIMARY KEY(manager_id, author_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE one_time_offer (id INT AUTO_INCREMENT NOT NULL, id_funnel INT DEFAULT NULL, full_price DOUBLE PRECISION DEFAULT NULL, discount_price DOUBLE PRECISION DEFAULT NULL, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_2B7EA838BD54433D (id_funnel), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_text (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE price_block_settings_courses (price_block_setting_id INT NOT NULL, course_id INT NOT NULL, INDEX IDX_16FCEABF70A3ABC6 (price_block_setting_id), INDEX IDX_16FCEABF591CC992 (course_id), PRIMARY KEY(price_block_setting_id, course_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_question (id INT AUTO_INCREMENT NOT NULL, id_lesson_element INT NOT NULL, question_text LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_6033B00B895AB198 (id_lesson_element), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quiz_question_answer (id INT AUTO_INCREMENT NOT NULL, id_quiz_question INT NOT NULL, title LONGTEXT NOT NULL COLLATE utf8_unicode_ci, is_right TINYINT(1) NOT NULL, INDEX IDX_E684DF7CDE1B616E (id_quiz_question), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_funnel_organic_price_block_setting (id INT AUTO_INCREMENT NOT NULL, sale_funnel_organic_id INT DEFAULT NULL, course_price_block_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, subscription_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, price DOUBLE PRECISION NOT NULL, INDEX IDX_27DB5FC21EDF53A6 (sale_funnel_organic_id), INDEX IDX_27DB5FC274975E2F (course_price_block_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_funnel_organic_price_block_thesis (id INT AUTO_INCREMENT NOT NULL, sale_funnel_organic_price_block_setting_id INT DEFAULT NULL, description VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_BD0DA69FD848CDFE (sale_funnel_organic_price_block_setting_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_funnel_organic_price_blocks (sale_funnel_organic_id INT NOT NULL, price_block_id INT NOT NULL, INDEX IDX_4998A4141EDF53A6 (sale_funnel_organic_id), INDEX IDX_4998A4148B5BB91B (price_block_id), PRIMARY KEY(sale_funnel_organic_id, price_block_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_author_club (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, discount DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_DE186DDD30A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_broken_basket (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, discount_percent DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_150E0E730A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_cross_sale (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, participate_author_club TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_3197CDCD591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_cross_sale_discount_course (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, funnel_cross_sale_id INT DEFAULT NULL, discount_percent DOUBLE PRECISION NOT NULL, UNIQUE INDEX course_funnel_cross_sale_unique (course_id, funnel_cross_sale_id), INDEX IDX_5C5D4913591CC992 (course_id), INDEX IDX_5C5D49132CFD1087 (funnel_cross_sale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_down_sell (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, price DOUBLE PRECISION NOT NULL, term INT NOT NULL, external_link VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_DD5FAB3E30A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_down_sell_lesson_sections (sales_funnel_down_sell_id INT NOT NULL, section_id INT NOT NULL, INDEX IDX_4875388DFE932430 (sales_funnel_down_sell_id), INDEX IDX_4875388DD823E37A (section_id), PRIMARY KEY(sales_funnel_down_sell_id, section_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_educational (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, lessons_file_id INT DEFAULT NULL, articles_file_id INT DEFAULT NULL, external_link VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_C4FFB87E30A9DA54 (id_course), INDEX IDX_C4FFB87ECB01A3BF (lessons_file_id), INDEX IDX_C4FFB87ED6AE1DCD (articles_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_educational_letters (sales_funnel_educational_id INT NOT NULL, letter_id INT NOT NULL, INDEX IDX_DD0CA23439304B93 (sales_funnel_educational_id), INDEX IDX_DD0CA2344525FF26 (letter_id), PRIMARY KEY(sales_funnel_educational_id, letter_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_hot_leads (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, installment_plan_months INT DEFAULT NULL, installment_plan TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_148E738B30A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_hot_leads_success_history (id INT AUTO_INCREMENT NOT NULL, funnel_hot_leads_id INT DEFAULT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_D14234827DC265AA (funnel_hot_leads_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_layer_cake (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, price DOUBLE PRECISION NOT NULL, INDEX IDX_3F0F6B5130A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_layer_cake_lesson_lessons (sales_funnel_layer_cake_id INT NOT NULL, lesson_id INT NOT NULL, INDEX IDX_A30DE0AF1D892E75 (sales_funnel_layer_cake_id), INDEX IDX_A30DE0AFCDF80196 (lesson_id), PRIMARY KEY(sales_funnel_layer_cake_id, lesson_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_layer_cake_lesson_sections (sales_funnel_layer_cake_id INT NOT NULL, section_id INT NOT NULL, INDEX IDX_926CD8691D892E75 (sales_funnel_layer_cake_id), INDEX IDX_926CD869D823E37A (section_id), PRIMARY KEY(sales_funnel_layer_cake_id, section_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_lead_collection (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, image_file_id INT DEFAULT NULL, other_file_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, lead_magnet_organic TINYINT(1) NOT NULL, lead_magnet_webinar TINYINT(1) NOT NULL, lead_magnet_education TINYINT(1) NOT NULL, lead_magnet_down_sell TINYINT(1) NOT NULL, lead_magnet_layer_cake TINYINT(1) NOT NULL, button_text VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, full_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_A20E334530A9DA54 (id_course), INDEX IDX_A20E33456DB2EB0 (image_file_id), INDEX IDX_A20E33458096E700 (other_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_mini_course (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_76E82EFB30A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_mini_course_lesson (id INT AUTO_INCREMENT NOT NULL, funnel_mini_course_id INT DEFAULT NULL, lesson_file_id INT DEFAULT NULL, homework_file_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, lesson_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, homework_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_C68EA4B5DC78FC4 (funnel_mini_course_id), INDEX IDX_C68EA4B66B72BCB (lesson_file_id), INDEX IDX_C68EA4BA5714EFD (homework_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_one_time_offer (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, video_file INT DEFAULT NULL, image_file INT DEFAULT NULL, offer_file INT DEFAULT NULL, level VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, for_webinar TINYINT(1) NOT NULL, for_lead_magnet TINYINT(1) NOT NULL, for_educational TINYINT(1) NOT NULL, for_mini_course TINYINT(1) NOT NULL, external_link VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, thank_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, video_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, additional_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, link LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_2F72D37830A9DA54 (id_course), INDEX IDX_2F72D3788B086BCC (video_file), INDEX IDX_2F72D3787EA5DC8E (image_file), INDEX IDX_2F72D37872671807 (offer_file), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, block1_image_banner_file_id INT DEFAULT NULL, block1_video_banner_file_id INT DEFAULT NULL, block2_course_image_file_id INT DEFAULT NULL, block4_photo_file_id INT DEFAULT NULL, block6_author_photo_file_id INT DEFAULT NULL, block6_author_video_file_id INT DEFAULT NULL, block8_photo_file_id INT DEFAULT NULL, block12_photo_signature_file_id INT DEFAULT NULL, block1_button_text VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block2_course_info LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, block4_title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block4_subtitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block4_button_text VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block5_type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block5_text LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, block6_author_info VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block6_author_experience LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, block6_author_video_from_banner TINYINT(1) NOT NULL, block8_title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block8_subtitle VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, block8_button_text VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, external_link VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_23DD4592591CC992 (course_id), INDEX IDX_23DD45926F20FD29 (block1_image_banner_file_id), INDEX IDX_23DD4592DE6460C3 (block1_video_banner_file_id), INDEX IDX_23DD4592C30EBDC5 (block2_course_image_file_id), INDEX IDX_23DD4592AD10C275 (block4_photo_file_id), INDEX IDX_23DD4592CF8FB5A0 (block6_author_photo_file_id), INDEX IDX_23DD45921F824B80 (block6_author_video_file_id), INDEX IDX_23DD4592E8E56B91 (block8_photo_file_id), INDEX IDX_23DD4592CF3602D2 (block12_photo_signature_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic_additional_block (sales_funnel_organic_id INT NOT NULL, additional_block_id INT NOT NULL, INDEX IDX_F6FB4B9FEDBABCA4 (sales_funnel_organic_id), INDEX IDX_F6FB4B9F533C3EDA (additional_block_id), PRIMARY KEY(sales_funnel_organic_id, additional_block_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic_company_logo (sales_funnel_organic_id INT NOT NULL, company_logo_id INT NOT NULL, INDEX IDX_41E8095DEDBABCA4 (sales_funnel_organic_id), INDEX IDX_41E8095DD9DD0E9D (company_logo_id), PRIMARY KEY(sales_funnel_organic_id, company_logo_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic_feed_back_video (sales_funnel_organic_id INT NOT NULL, feedback_id INT NOT NULL, INDEX IDX_C6AEAA98EDBABCA4 (sales_funnel_organic_id), INDEX IDX_C6AEAA98D249A887 (feedback_id), PRIMARY KEY(sales_funnel_organic_id, feedback_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic_payment_text (sales_funnel_organic_id INT NOT NULL, payment_text_id INT NOT NULL, INDEX IDX_FC03B913EDBABCA4 (sales_funnel_organic_id), INDEX IDX_FC03B91370C43BA2 (payment_text_id), PRIMARY KEY(sales_funnel_organic_id, payment_text_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_organic_skills (sales_funnel_organic_id INT NOT NULL, skill_id INT NOT NULL, INDEX IDX_C822B601EDBABCA4 (sales_funnel_organic_id), INDEX IDX_C822B6015585C142 (skill_id), PRIMARY KEY(sales_funnel_organic_id, skill_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_partner (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, partner VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, award_percent DOUBLE PRECISION NOT NULL, INDEX IDX_3ECB092130A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_post_sale (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, activate_after_days TINYINT(1) NOT NULL, discount_percent DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_4A4ADD530A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_walker_start (id INT AUTO_INCREMENT NOT NULL, id_course INT DEFAULT NULL, UNIQUE INDEX UNIQ_B84803E730A9DA54 (id_course), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, image_banner_file_id INT DEFAULT NULL, video_banner_file_id INT DEFAULT NULL, b2_homework_file_id INT DEFAULT NULL, b2_workbook_file_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, time DATETIME DEFAULT NULL, timezone VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, block2homework_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, block2_work_book_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, price DOUBLE PRECISION NOT NULL, auto_webinar TINYINT(1) NOT NULL, webinar_record TINYINT(1) NOT NULL, webinar_record_price DOUBLE PRECISION NOT NULL, webinar_record_access_days INT NOT NULL, external_link VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, offer_description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, INDEX IDX_C602A87D591CC992 (course_id), INDEX IDX_C602A87D500087C5 (image_banner_file_id), INDEX IDX_C602A87DE1441A2F (video_banner_file_id), INDEX IDX_C602A87D765E10FD (b2_homework_file_id), INDEX IDX_C602A87D92B85DC7 (b2_workbook_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar_bonuses (sales_funnel_webinar_id INT NOT NULL, bonus_id INT NOT NULL, INDEX IDX_99F18B97B2B86938 (sales_funnel_webinar_id), INDEX IDX_99F18B9769545666 (bonus_id), PRIMARY KEY(sales_funnel_webinar_id, bonus_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar_funnel_down_sell (sales_funnel_webinar_id INT NOT NULL, sale_funnel_down_sell_id INT NOT NULL, INDEX IDX_C4BB4318B2B86938 (sales_funnel_webinar_id), INDEX IDX_C4BB4318FC104A3E (sale_funnel_down_sell_id), PRIMARY KEY(sales_funnel_webinar_id, sale_funnel_down_sell_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar_offer (sales_funnel_webinar_id INT NOT NULL, offer_id INT NOT NULL, INDEX IDX_6B2E8393B2B86938 (sales_funnel_webinar_id), INDEX IDX_6B2E839353C674EE (offer_id), PRIMARY KEY(sales_funnel_webinar_id, offer_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar_promo_codes (sales_funnel_webinar_id INT NOT NULL, promo_code_id INT NOT NULL, INDEX IDX_6C4A3ECDB2B86938 (sales_funnel_webinar_id), INDEX IDX_6C4A3ECD2FAE4625 (promo_code_id), PRIMARY KEY(sales_funnel_webinar_id, promo_code_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sales_funnel_webinar_theses (sales_funnel_webinar_id INT NOT NULL, thesis_id INT NOT NULL, INDEX IDX_ABDF9BF5B2B86938 (sales_funnel_webinar_id), INDEX IDX_ABDF9BF568D82738 (thesis_id), PRIMARY KEY(sales_funnel_webinar_id, thesis_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_comment (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, hook_event_id INT NOT NULL, course_id INT NOT NULL, lecture_id INT DEFAULT NULL, student_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, comment_id BIGINT NOT NULL, full_url VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, comment_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, rating INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_course_student (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, course_id INT NOT NULL, course_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, student_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, last_activity_at DATETIME DEFAULT NULL, last_sign_in_at DATETIME DEFAULT NULL, UNIQUE INDEX course_student_unique_idx (course_id, student_email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_enrollment (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, hook_event_id INT NOT NULL, course_id INT NOT NULL, course_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, student_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, last_activity_at DATETIME NOT NULL, last_signed_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_lecture_progress (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, hook_event_id INT NOT NULL, course_id INT NOT NULL, course_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, student_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, last_signed_at DATETIME NOT NULL, lecture_id INT DEFAULT NULL, percent_complete INT DEFAULT NULL, comments_rating INT NOT NULL, correct_answers INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_quiz_response (id INT AUTO_INCREMENT NOT NULL, created_at DATETIME NOT NULL, hook_event_id INT NOT NULL, course_id INT DEFAULT NULL, lecture_id INT DEFAULT NULL, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, quiz_id INT NOT NULL, correct_answers INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_transaction (id INT AUTO_INCREMENT NOT NULL, internal_course_id INT DEFAULT NULL, teachable_student_id INT DEFAULT NULL, created_at DATETIME NOT NULL, hook_event_id INT NOT NULL, transaction_id INT NOT NULL, final_price BIGINT NOT NULL, currency VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, status VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, affiliate_fees BIGINT NOT NULL, is_chargeback INT DEFAULT NULL, author_id INT DEFAULT NULL, course_id INT NOT NULL, course_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, product_plan VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, student_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, student_email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, affiliate_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, income BIGINT NOT NULL, refund_amount BIGINT DEFAULT NULL, imported_from_csv TINYINT(1) NOT NULL, INDEX IDX_C452625CD1DB31F9 (internal_course_id), INDEX IDX_C452625CC8DEFF25 (teachable_student_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teachable_transaction_refunded (id INT AUTO_INCREMENT NOT NULL, hook_event_id INT NOT NULL, transaction_id INT NOT NULL, created_at DATETIME NOT NULL, amount_refunded BIGINT DEFAULT NULL, imported_from_csv TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE upload_care (id INT AUTO_INCREMENT NOT NULL, file_uuid VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, file_cdn VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, file_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, source VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dropbox_async_job_id VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dropbox_file_path VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_comment_created (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_enrollment_created (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_lecture_progress_created (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_response_created (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_transaction_created (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webhook_teachable_transaction_refunded (id INT AUTO_INCREMENT NOT NULL, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, referer VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, dateCreatedAt DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webinar_bonus (id INT AUTO_INCREMENT NOT NULL, bonus_file_id INT DEFAULT NULL, title LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_A3D2E5162509164 (bonus_file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webinar_date (id INT AUTO_INCREMENT NOT NULL, webinar_id INT DEFAULT NULL, time DATETIME NOT NULL, timezone VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_B0859EB2A391D86E (webinar_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webinar_offer (id INT AUTO_INCREMENT NOT NULL, title LONGTEXT NOT NULL COLLATE utf8_unicode_ci, price DOUBLE PRECISION NOT NULL, months INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webinar_promo_code (id INT AUTO_INCREMENT NOT NULL, code LONGTEXT NOT NULL COLLATE utf8_unicode_ci, price DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE webinar_thesis (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE action_log');
        $this->addSql('DROP TABLE additional_block');
        $this->addSql('DROP TABLE company_logo');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE course_block');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE customer_action');
        $this->addSql('DROP TABLE customer_packet');
        $this->addSql('DROP TABLE customer_payment');
        $this->addSql('DROP TABLE customer_payment_account');
        $this->addSql('DROP TABLE customer_payment_report');
        $this->addSql('DROP TABLE customer_role');
        $this->addSql('DROP TABLE customer_transferwise_account');
        $this->addSql('DROP TABLE educational_letter');
        $this->addSql('DROP TABLE feedback_video');
        $this->addSql('DROP TABLE funnel_priority');
        $this->addSql('DROP TABLE knowledge_skills');
        $this->addSql('DROP TABLE lesson');
        $this->addSql('DROP TABLE lesson_element');
        $this->addSql('DROP TABLE lesson_section');
        $this->addSql('DROP TABLE lesson_sections_price_blocks');
        $this->addSql('DROP TABLE managers_authors');
        $this->addSql('DROP TABLE one_time_offer');
        $this->addSql('DROP TABLE payment_text');
        $this->addSql('DROP TABLE price_block_settings_courses');
        $this->addSql('DROP TABLE quiz_question');
        $this->addSql('DROP TABLE quiz_question_answer');
        $this->addSql('DROP TABLE sale_funnel_organic_price_block_setting');
        $this->addSql('DROP TABLE sale_funnel_organic_price_block_thesis');
        $this->addSql('DROP TABLE sale_funnel_organic_price_blocks');
        $this->addSql('DROP TABLE sales_funnel_author_club');
        $this->addSql('DROP TABLE sales_funnel_broken_basket');
        $this->addSql('DROP TABLE sales_funnel_cross_sale');
        $this->addSql('DROP TABLE sales_funnel_cross_sale_discount_course');
        $this->addSql('DROP TABLE sales_funnel_down_sell');
        $this->addSql('DROP TABLE sales_funnel_down_sell_lesson_sections');
        $this->addSql('DROP TABLE sales_funnel_educational');
        $this->addSql('DROP TABLE sales_funnel_educational_letters');
        $this->addSql('DROP TABLE sales_funnel_hot_leads');
        $this->addSql('DROP TABLE sales_funnel_hot_leads_success_history');
        $this->addSql('DROP TABLE sales_funnel_layer_cake');
        $this->addSql('DROP TABLE sales_funnel_layer_cake_lesson_lessons');
        $this->addSql('DROP TABLE sales_funnel_layer_cake_lesson_sections');
        $this->addSql('DROP TABLE sales_funnel_lead_collection');
        $this->addSql('DROP TABLE sales_funnel_mini_course');
        $this->addSql('DROP TABLE sales_funnel_mini_course_lesson');
        $this->addSql('DROP TABLE sales_funnel_one_time_offer');
        $this->addSql('DROP TABLE sales_funnel_organic');
        $this->addSql('DROP TABLE sales_funnel_organic_additional_block');
        $this->addSql('DROP TABLE sales_funnel_organic_company_logo');
        $this->addSql('DROP TABLE sales_funnel_organic_feed_back_video');
        $this->addSql('DROP TABLE sales_funnel_organic_payment_text');
        $this->addSql('DROP TABLE sales_funnel_organic_skills');
        $this->addSql('DROP TABLE sales_funnel_partner');
        $this->addSql('DROP TABLE sales_funnel_post_sale');
        $this->addSql('DROP TABLE sales_funnel_walker_start');
        $this->addSql('DROP TABLE sales_funnel_webinar');
        $this->addSql('DROP TABLE sales_funnel_webinar_bonuses');
        $this->addSql('DROP TABLE sales_funnel_webinar_funnel_down_sell');
        $this->addSql('DROP TABLE sales_funnel_webinar_offer');
        $this->addSql('DROP TABLE sales_funnel_webinar_promo_codes');
        $this->addSql('DROP TABLE sales_funnel_webinar_theses');
        $this->addSql('DROP TABLE teachable_comment');
        $this->addSql('DROP TABLE teachable_course_student');
        $this->addSql('DROP TABLE teachable_enrollment');
        $this->addSql('DROP TABLE teachable_lecture_progress');
        $this->addSql('DROP TABLE teachable_quiz_response');
        $this->addSql('DROP TABLE teachable_transaction');
        $this->addSql('DROP TABLE teachable_transaction_refunded');
        $this->addSql('DROP TABLE upload_care');
        $this->addSql('DROP TABLE webhook');
        $this->addSql('DROP TABLE webhook_teachable_comment_created');
        $this->addSql('DROP TABLE webhook_teachable_enrollment_created');
        $this->addSql('DROP TABLE webhook_teachable_lecture_progress_created');
        $this->addSql('DROP TABLE webhook_teachable_response_created');
        $this->addSql('DROP TABLE webhook_teachable_transaction_created');
        $this->addSql('DROP TABLE webhook_teachable_transaction_refunded');
        $this->addSql('DROP TABLE webinar_bonus');
        $this->addSql('DROP TABLE webinar_date');
        $this->addSql('DROP TABLE webinar_offer');
        $this->addSql('DROP TABLE webinar_promo_code');
        $this->addSql('DROP TABLE webinar_thesis');
    }
}
