services:
    hb.admin.controller.sale_funnel.down.list:
        class: HB\AdminBundle\Controller\SaleFunnel\DownSell\ListController
        arguments:
            - "@twig"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@access.service"
            - "@session.flash_bag"

    hb.admin.controller.sale_funnel.down.remove:
        class: HB\AdminBundle\Controller\SaleFunnel\DownSell\RemoveController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@access.service"

    hb.admin.controller.sale_funnel.down.edit:
        class: HB\AdminBundle\Controller\SaleFunnel\DownSell\EditController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@form.factory"
            - "@twig"
            - "@access.service"
            - "@session.flash_bag"
