services:
    hb.admin.controller.sale_funnel.mini_course.create:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\CreateController
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.remove:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\RemoveController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@upload_care.service"
            - "@router"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.edit:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\EditController
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@form.factory"
            - "@form.handler"
            - "@session.flash_bag"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.remove_lesson:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\RemoveLessonController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@upload_care.service"
            - "@router"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.edit_lesson:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\EditLessonController
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
            - "@twig"
            - "@form.factory"
            - "@form.handler"
            - "@session.flash_bag"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.edit_lesson.files_block:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\BlockLessonFilesController
        arguments:
            - "@twig"

    hb.admin.controller.sale_funnel.mini_course.update.file_homework:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\UpdateFileHomeWorkController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@upload_care.service"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.update.file_lesson:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\UpdateFileLessonController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@upload_care.service"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.remove.file_lesson:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\RemoveFileLessonController
        arguments:
            - "@upload_care.service"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@access.service"

    hb.admin.controller.sale_funnel.mini_course.remove.file_homework:
        class: HB\AdminBundle\Controller\SaleFunnel\MiniCourse\RemoveFileHomeworkController
        arguments:
            - "@upload_care.service"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@access.service"
