<?php

namespace HB\AdminBundle\Repository;

/**
 * CustomerActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnviewedActionsCount()
    {
        $dql = 'select count(act.id) from HBAdminBundle:CustomerAction act where act.isViewed = false';
        return $this->getEntityManager()->createQuery($dql)
            ->getSingleScalarResult();
    }

    public function getUnviewedActions()
    {
        $dql = 'select act from HBAdminBundle:CustomerAction act where act.isViewed = false';
        return $this->getEntityManager()->createQuery($dql)->getResult();
    }
}
