<?php

namespace HB\AdminBundle\Repository;
use HB\AdminBundle\Entity\Course;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLessonsQueryByCourse(Course $course)
    {
        $dql = 'select lesson from HBAdminBundle:Lesson lesson where lesson.course = :course';
        $query = $this->getEntityManager()->createQuery($dql);
        $query->setParameter('course', $course);

        return $query;
    }
}
